# Generated by Django 4.2.20 on 2025-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('valor_hora', models.FloatField(max_length=4, verbose_name='Valor por hora')),
                ('modalidade_contrato', models.CharField(choices=[('diarista', 'Diarista'), ('mensalista', 'Mensalista')], default='diarista', max_length=10, verbose_name='Modalidade do contrato')),
                ('situacao_cadastro', models.CharField(choices=[('AT', 'Ativo'), ('DTDesativado', 'Desativado')], default='AT', max_length=12, verbose_name='Situação do cadastro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
